import java.util.*;

public class Hint {
    private static Map<String, String> NFLSkillPosition = new HashMap<>();
    private static Map<String, String> ModernNFL = new HashMap<>();
    private static Map<String, String> ModernNHL = new HashMap<>();
    private static Map<String, String> AllTimeNHL = new HashMap<>();

    public Hint() {
        NFLSkillPosition = new HashMap<>();
        ModernNFL = new HashMap<>();
        ModernNHL = new HashMap<>();
        AllTimeNHL = new HashMap<>();
    }

    public static Map<String, String> selectMap(String category) {
        switch (category) {
            case "NFL Skill Postions":
                initNFLSkillPostion();
                return  NFLSkillPosition;

            case "Modern NFL":
                initModernNFL();
                return  ModernNFL;

            case "Modern NHL":
                initModernNHL();
                return  ModernNHL;

            case "All Time NHL":
                initAllTimeNHL();
                return  AllTimeNHL;

            default:
                return null;
        }
    }

    private static void initAllTimeNHL() {
        AllTimeNHL.put("Wayne Gretzky", "Forward");
        AllTimeNHL.put("Mario Lemieux", "Forward");
        AllTimeNHL.put("Gordie Howe", "Forward");
        AllTimeNHL.put("Sidney Crosby", "Forward");
        AllTimeNHL.put("Alex Ovechkin", "Forward");
        AllTimeNHL.put("Jaromir Jagr", "Forward");
        AllTimeNHL.put("Mark Messier", "Forward");
        AllTimeNHL.put("Steve Yzerman", "Forward");
        AllTimeNHL.put("Joe Sakic", "Forward");
        AllTimeNHL.put("Maurice Richard", "Forward");
        AllTimeNHL.put("Jean Beliveau", "Forward");
        AllTimeNHL.put("Guy Lafleur", "Forward");
        AllTimeNHL.put("Mike Bossy", "Forward");
        AllTimeNHL.put("Phil Esposito", "Forward");
        AllTimeNHL.put("Brett Hull", "Forward");
        AllTimeNHL.put("Teemu Selanne", "Forward");
        AllTimeNHL.put("Stan Mikita", "Forward");
        AllTimeNHL.put("Bobby Hull", "Forward");
        AllTimeNHL.put("Peter Forsberg", "Forward");
        AllTimeNHL.put("Eric Lindros", "Forward");
        AllTimeNHL.put("Paul Kariya", "Forward");
        AllTimeNHL.put("Pat LaFontaine", "Forward");
        AllTimeNHL.put("Dale Hawerchuk", "Forward");
        AllTimeNHL.put("Marcel Dionne", "Forward");
        AllTimeNHL.put("Gilbert Perreault", "Forward");
        AllTimeNHL.put("Bryan Trottier", "Forward");
        AllTimeNHL.put("Denis Savard", "Forward");
        AllTimeNHL.put("Ron Francis", "Forward");
        AllTimeNHL.put("Mike Modano", "Forward");
        AllTimeNHL.put("Joe Thornton", "Forward");
        AllTimeNHL.put("Patrick Kane", "Forward");
        AllTimeNHL.put("Evgeni Malkin", "Forward");
        AllTimeNHL.put("Steven Stamkos", "Forward");
        AllTimeNHL.put("Connor McDavid", "Forward");
        AllTimeNHL.put("Auston Matthews", "Forward");
        AllTimeNHL.put("Nathan MacKinnon", "Forward");
        AllTimeNHL.put("Leon Draisaitl", "Forward");
        AllTimeNHL.put("Jonathan Toews", "Forward");
        AllTimeNHL.put("Anze Kopitar", "Forward");
        AllTimeNHL.put("Martin St. Louis", "Forward");
        AllTimeNHL.put("Brendan Shanahan", "Forward");
        AllTimeNHL.put("Dany Heatley", "Forward");
        AllTimeNHL.put("Ilya Kovalchuk", "Forward");
        AllTimeNHL.put("Pavel Bure", "Forward");
        AllTimeNHL.put("Sergei Fedorov", "Forward");
        AllTimeNHL.put("Alexander Mogilny", "Forward");
        AllTimeNHL.put("Pavel Datsyuk", "Forward");
        AllTimeNHL.put("Henrik Zetterberg", "Forward");
        AllTimeNHL.put("Daniel Sedin", "Forward");
        AllTimeNHL.put("Henrik Sedin", "Forward");
        AllTimeNHL.put("Mats Sundin", "Forward");
        AllTimeNHL.put("Peter Bondra", "Forward");
        AllTimeNHL.put("Keith Tkachuk", "Forward");
        AllTimeNHL.put("Jeremy Roenick", "Forward");

        // Defense/Goalie
        AllTimeNHL.put("Bobby Orr", "Defense/Goalie");
        AllTimeNHL.put("Nicklas Lidstrom", "Defense/Goalie");
        AllTimeNHL.put("Ray Bourque", "Defense/Goalie");
        AllTimeNHL.put("Larry Robinson", "Defense/Goalie");
        AllTimeNHL.put("Doug Harvey", "Defense/Goalie");
        AllTimeNHL.put("Denis Potvin", "Defense/Goalie");
        AllTimeNHL.put("Chris Chelios", "Defense/Goalie");
        AllTimeNHL.put("Scott Stevens", "Defense/Goalie");
        AllTimeNHL.put("Scott Niedermayer", "Defense/Goalie");
        AllTimeNHL.put("Al MacInnis", "Defense/Goalie");
        AllTimeNHL.put("Paul Coffey", "Defense/Goalie");
        AllTimeNHL.put("Brian Leetch", "Defense/Goalie");
        AllTimeNHL.put("Rod Langway", "Defense/Goalie");
        AllTimeNHL.put("Brad Park", "Defense/Goalie");
        AllTimeNHL.put("Sergei Zubov", "Defense/Goalie");
        AllTimeNHL.put("Chris Pronger", "Defense/Goalie");
        AllTimeNHL.put("Zdeno Chara", "Defense/Goalie");
        AllTimeNHL.put("Duncan Keith", "Defense/Goalie");
        AllTimeNHL.put("Mark Howe", "Defense/Goalie");
        AllTimeNHL.put("Pierre Pilote", "Defense/Goalie");
        AllTimeNHL.put("Tim Horton", "Defense/Goalie");
        AllTimeNHL.put("Cale Makar", "Defense/Goalie");
        AllTimeNHL.put("Victor Hedman", "Defense/Goalie");
        AllTimeNHL.put("Roman Josi", "Defense/Goalie");
        AllTimeNHL.put("Erik Karlsson", "Defense/Goalie");
        AllTimeNHL.put("Brent Burns", "Defense/Goalie");
        AllTimeNHL.put("Drew Doughty", "Defense/Goalie");
        AllTimeNHL.put("Adam Fox", "Defense/Goalie");
        AllTimeNHL.put("Quinn Hughes", "Defense/Goalie");
        AllTimeNHL.put("Red Kelly", "Defense/Goalie");
        AllTimeNHL.put("King Clancy", "Defense/Goalie");
        AllTimeNHL.put("Eddie Shore", "Defense/Goalie");
        AllTimeNHL.put("Bobby Baun", "Defense/Goalie");
        AllTimeNHL.put("Martin Brodeur", "Defense/Goalie");
        AllTimeNHL.put("Patrick Roy", "Defense/Goalie");
        AllTimeNHL.put("Dominik Hasek", "Defense/Goalie");
        AllTimeNHL.put("Terry Sawchuk", "Defense/Goalie");
        AllTimeNHL.put("Jacques Plante", "Defense/Goalie");
        AllTimeNHL.put("Ken Dryden", "Defense/Goalie");
        AllTimeNHL.put("Grant Fuhr", "Defense/Goalie");
        AllTimeNHL.put("Tony Esposito", "Defense/Goalie");
        AllTimeNHL.put("Ed Belfour", "Defense/Goalie");
        AllTimeNHL.put("Roberto Luongo", "Defense/Goalie");
        AllTimeNHL.put("Carey Price", "Defense/Goalie");
        AllTimeNHL.put("Glenn Hall", "Defense/Goalie");
        AllTimeNHL.put("Billy Smith", "Defense/Goalie");
        AllTimeNHL.put("Bernie Parent", "Defense/Goalie");
        AllTimeNHL.put("Mike Richter", "Defense/Goalie");
        AllTimeNHL.put("Tom Barrasso", "Defense/Goalie");
        AllTimeNHL.put("Curtis Joseph", "Defense/Goalie");
        AllTimeNHL.put("Olaf Kolzig", "Defense/Goalie");
        AllTimeNHL.put("Pekka Rinne", "Defense/Goalie");
        AllTimeNHL.put("Henrik Lundqvist", "Defense/Goalie");
        AllTimeNHL.put("Marc-Andre Fleury", "Defense/Goalie");
        AllTimeNHL.put("Andrei Vasilevskiy", "Defense/Goalie");
        AllTimeNHL.put("Igor Shesterkin", "Defense/Goalie");
    }

    private static void initModernNHL() {
        // Forwards
        ModernNHL.put("Connor McDavid", "Forward");
        ModernNHL.put("Auston Matthews", "Forward");
        ModernNHL.put("Nathan MacKinnon", "Forward");
        ModernNHL.put("Leon Draisaitl", "Forward");
        ModernNHL.put("David Pastrnak", "Forward");
        ModernNHL.put("Nikita Kucherov", "Forward");
        ModernNHL.put("Jack Hughes", "Forward");
        ModernNHL.put("Jason Robertson", "Forward");
        ModernNHL.put("Mikko Rantanen", "Forward");
        ModernNHL.put("Matthew Tkachuk", "Forward");
        ModernNHL.put("Brady Tkachuk", "Forward");
        ModernNHL.put("Sidney Crosby", "Forward");
        ModernNHL.put("Alex Ovechkin", "Forward");
        ModernNHL.put("Elias Pettersson", "Forward");
        ModernNHL.put("Mitch Marner", "Forward");
        ModernNHL.put("William Nylander", "Forward");
        ModernNHL.put("Connor Bedard", "Forward");
        ModernNHL.put("Matvei Michkov", "Forward");
        ModernNHL.put("Logan Cooley", "Forward");
        ModernNHL.put("Leo Carlsson", "Forward");
        ModernNHL.put("Adam Fantilli", "Forward");
        ModernNHL.put("Cole Caufield", "Forward");
        ModernNHL.put("Mason McTavish", "Forward");
        ModernNHL.put("Juraj Slafkovsky", "Forward");
        ModernNHL.put("Shane Wright", "Forward");
        ModernNHL.put("Dylan Holloway", "Forward");
        ModernNHL.put("J.T. Miller", "Forward");
        ModernNHL.put("Steven Stamkos", "Forward");
        ModernNHL.put("Brayden Point", "Forward");
        ModernNHL.put("Kyle Connor", "Forward");
        ModernNHL.put("Jake Guentzel", "Forward");
        ModernNHL.put("Mark Scheifele", "Forward");
        ModernNHL.put("John Tavares", "Forward");
        ModernNHL.put("Anze Kopitar", "Forward");
        ModernNHL.put("Jonathan Huberdeau", "Forward");
        ModernNHL.put("Johnny Gaudreau", "Forward");
        ModernNHL.put("Patrik Laine", "Forward");
        ModernNHL.put("Timo Meier", "Forward");
        ModernNHL.put("Clayton Keller", "Forward");
        ModernNHL.put("Jesper Bratt", "Forward");
        ModernNHL.put("Roope Hintz", "Forward");
        ModernNHL.put("Aleksander Barkov", "Forward");
        ModernNHL.put("Sebastian Aho", "Forward");
        ModernNHL.put("Mathew Barzal", "Forward");
        ModernNHL.put("Jack Eichel", "Forward");
        ModernNHL.put("Ryan O'Reilly", "Forward");
        ModernNHL.put("Mika Zibanejad", "Forward");
        ModernNHL.put("Bo Horvat", "Forward");
        ModernNHL.put("Nico Hischier", "Forward");
        ModernNHL.put("Dylan Larkin", "Forward");
        ModernNHL.put("Pierre-Luc Dubois", "Forward");
        ModernNHL.put("Robert Thomas", "Forward");
        ModernNHL.put("Jordan Kyrou", "Forward");
        ModernNHL.put("Zach Hyman", "Forward");
        ModernNHL.put("Valeri Nichushkin", "Forward");
        ModernNHL.put("Tom Wilson", "Forward");
        ModernNHL.put("Kirill Kaprizov", "Forward");
        ModernNHL.put("Artemi Panarin", "Forward");
        ModernNHL.put("Filip Forsberg", "Forward");
        ModernNHL.put("Travis Konecny", "Forward");
        ModernNHL.put("Alex DeBrincat", "Forward");
        ModernNHL.put("Kevin Fiala", "Forward");
        ModernNHL.put("Troy Terry", "Forward");
        ModernNHL.put("Joel Eriksson Ek", "Forward");
        ModernNHL.put("Pavel Buchnevich", "Forward");
        ModernNHL.put("Matt Boldy", "Forward");
        ModernNHL.put("Dawson Mercer", "Forward");
        ModernNHL.put("Cole Perfetti", "Forward");
        ModernNHL.put("Kent Johnson", "Forward");
        ModernNHL.put("Marco Rossi", "Forward");
        ModernNHL.put("Peyton Krebs", "Forward");
        ModernNHL.put("William Eklund", "Forward");
        ModernNHL.put("Patrice Bergeron", "Forward");
        ModernNHL.put("Mark Stone", "Forward");
        ModernNHL.put("Joe Pavelski", "Forward");
        ModernNHL.put("Yanni Gourde", "Forward");
        ModernNHL.put("Blake Coleman", "Forward");
        ModernNHL.put("Barclay Goodrow", "Forward");
        ModernNHL.put("Chandler Stephenson", "Forward");
        ModernNHL.put("Nicholas Paul", "Forward");
        ModernNHL.put("Trevor Zegras", "Forward");
        ModernNHL.put("Lawson Crouse", "Forward");
        ModernNHL.put("Jordan Greenway", "Forward");
        ModernNHL.put("Zach Aston-Reese", "Forward");
        ModernNHL.put("Trent Frederic", "Forward");
        ModernNHL.put("Max Comtois", "Forward");
        ModernNHL.put("Robby Fabbri", "Forward");

        // Defense/Goalie
        ModernNHL.put("Cale Makar", "Defense/Goalie");
        ModernNHL.put("Quinn Hughes", "Defense/Goalie");
        ModernNHL.put("Adam Fox", "Defense/Goalie");
        ModernNHL.put("Victor Hedman", "Defense/Goalie");
        ModernNHL.put("Roman Josi", "Defense/Goalie");
        ModernNHL.put("Miro Heiskanen", "Defense/Goalie");
        ModernNHL.put("Charlie McAvoy", "Defense/Goalie");
        ModernNHL.put("Devon Toews", "Defense/Goalie");
        ModernNHL.put("Evan Bouchard", "Defense/Goalie");
        ModernNHL.put("Noah Dobson", "Defense/Goalie");
        ModernNHL.put("Josh Morrissey", "Defense/Goalie");
        ModernNHL.put("Moritz Seider", "Defense/Goalie");
        ModernNHL.put("Rasmus Dahlin", "Defense/Goalie");
        ModernNHL.put("K'Andre Miller", "Defense/Goalie");
        ModernNHL.put("Jake Sanderson", "Defense/Goalie");
        ModernNHL.put("Owen Power", "Defense/Goalie");
        ModernNHL.put("Brandon Montour", "Defense/Goalie");
        ModernNHL.put("Luke Hughes", "Defense/Goalie");
        ModernNHL.put("Simon Nemec", "Defense/Goalie");
        ModernNHL.put("Jamie Drysdale", "Defense/Goalie");
        ModernNHL.put("Philip Broberg", "Defense/Goalie");
        ModernNHL.put("Simon Edvinsson", "Defense/Goalie");
        ModernNHL.put("Brandt Clarke", "Defense/Goalie");
        ModernNHL.put("Kevin Korchinski", "Defense/Goalie");
        ModernNHL.put("David Jiricek", "Defense/Goalie");
        ModernNHL.put("Drew Doughty", "Defense/Goalie");
        ModernNHL.put("Brent Burns", "Defense/Goalie");
        ModernNHL.put("Erik Karlsson", "Defense/Goalie");
        ModernNHL.put("Jeff Petry", "Defense/Goalie");
        ModernNHL.put("Jaccob Slavin", "Defense/Goalie");
        ModernNHL.put("Jonas Brodin", "Defense/Goalie");
        ModernNHL.put("Ryan Lindgren", "Defense/Goalie");
        ModernNHL.put("Shea Theodore", "Defense/Goalie");
        ModernNHL.put("Tony DeAngelo", "Defense/Goalie");
        ModernNHL.put("John Klingberg", "Defense/Goalie");
        ModernNHL.put("Tyson Barrie", "Defense/Goalie");
        ModernNHL.put("Samuel Girard", "Defense/Goalie");
        ModernNHL.put("Mike Matheson", "Defense/Goalie");
        ModernNHL.put("Cam Fowler", "Defense/Goalie");
        ModernNHL.put("Vince Dunn", "Defense/Goalie");
        ModernNHL.put("Igor Shesterkin", "Defense/Goalie");
        ModernNHL.put("Andrei Vasilevskiy", "Defense/Goalie");
        ModernNHL.put("Ilya Sorokin", "Defense/Goalie");
        ModernNHL.put("Jake Oettinger", "Defense/Goalie");
        ModernNHL.put("Jeremy Swayman", "Defense/Goalie");
        ModernNHL.put("Thatcher Demko", "Defense/Goalie");
        ModernNHL.put("Connor Hellebuyck", "Defense/Goalie");
        ModernNHL.put("Juuse Saros", "Defense/Goalie");
        ModernNHL.put("Filip Gustavsson", "Defense/Goalie");
        ModernNHL.put("Stuart Skinner", "Defense/Goalie");
        ModernNHL.put("Alexandar Georgiev", "Defense/Goalie");
        ModernNHL.put("Carter Hart", "Defense/Goalie");
        ModernNHL.put("Linus Ullmark", "Defense/Goalie");
        ModernNHL.put("Cam Talbot", "Defense/Goalie");
        ModernNHL.put("Vitek Vanecek", "Defense/Goalie");
        ModernNHL.put("Pheonix Copley", "Defense/Goalie");
        ModernNHL.put("Charlie Lindgren", "Defense/Goalie");
        ModernNHL.put("Dan Vladar", "Defense/Goalie");
        ModernNHL.put("Antti Raanta", "Defense/Goalie");
        ModernNHL.put("Martin Jones", "Defense/Goalie");
        ModernNHL.put("Jonathan Quick", "Defense/Goalie");
    }

    private static void initModernNFL() {
        // Quarterbacks (35)
        ModernNFL.put("Patrick Mahomes", "AFC - Offense");
        ModernNFL.put("Josh Allen", "AFC - Offense");
        ModernNFL.put("Joe Burrow", "AFC - Offense");
        ModernNFL.put("Lamar Jackson", "AFC - Offense");
        ModernNFL.put("Justin Herbert", "AFC - Offense");
        ModernNFL.put("C.J. Stroud", "AFC - Offense");
        ModernNFL.put("Trevor Lawrence", "AFC - Offense");
        ModernNFL.put("Anthony Richardson", "AFC - Offense");
        ModernNFL.put("Tua Tagovailoa", "AFC - Offense");
        ModernNFL.put("Will Levis", "AFC - Offense");
        ModernNFL.put("Bryce Young", "NFC - Offense");
        ModernNFL.put("Jalen Hurts", "NFC - Offense");
        ModernNFL.put("Dak Prescott", "NFC - Offense");
        ModernNFL.put("Jordan Love", "NFC - Offense");
        ModernNFL.put("Kyler Murray", "NFC - Offense");
        ModernNFL.put("Brock Purdy", "NFC - Offense");
        ModernNFL.put("Matthew Stafford", "NFC - Offense");
        ModernNFL.put("Jared Goff", "NFC - Offense");
        ModernNFL.put("Kirk Cousins", "NFC - Offense");
        ModernNFL.put("Geno Smith", "NFC - Offense");
        ModernNFL.put("Daniel Jones", "NFC - Offense");
        ModernNFL.put("Caleb Williams", "NFC - Offense");
        ModernNFL.put("Drake Maye", "AFC - Offense");
        ModernNFL.put("Jayden Daniels", "NFC - Offense");
        ModernNFL.put("Kenny Pickett", "AFC - Offense");
        ModernNFL.put("Mac Jones", "AFC - Offense");
        ModernNFL.put("Desmond Ridder", "NFC - Offense");
        ModernNFL.put("Sam Howell", "NFC - Offense");
        ModernNFL.put("Aidan O'Connell", "AFC - Offense");
        ModernNFL.put("Jake Browning", "AFC - Offense");
        ModernNFL.put("Dorian Thompson-Robinson", "AFC - Offense");
        ModernNFL.put("Easton Stick", "AFC - Offense");
        ModernNFL.put("Tanner McKee", "NFC - Offense");
        ModernNFL.put("Stetson Bennett", "NFC - Offense");
        ModernNFL.put("Malik Willis", "AFC - Offense");

// Running Backs (40)
        ModernNFL.put("Christian McCaffrey", "NFC - Offense");
        ModernNFL.put("Bijan Robinson", "NFC - Offense");
        ModernNFL.put("Jahmyr Gibbs", "NFC - Offense");
        ModernNFL.put("Saquon Barkley", "NFC - Offense");
        ModernNFL.put("Travis Etienne", "AFC - Offense");
        ModernNFL.put("Jonathan Taylor", "AFC - Offense");
        ModernNFL.put("Nick Chubb", "AFC - Offense");
        ModernNFL.put("Josh Jacobs", "NFC - Offense");
        ModernNFL.put("Derrick Henry", "AFC - Offense");
        ModernNFL.put("Tony Pollard", "AFC - Offense");
        ModernNFL.put("Rhamondre Stevenson", "AFC - Offense");
        ModernNFL.put("James Cook", "AFC - Offense");
        ModernNFL.put("Kenneth Walker", "NFC - Offense");
        ModernNFL.put("Javonte Williams", "AFC - Offense");
        ModernNFL.put("Isiah Pacheco", "AFC - Offense");
        ModernNFL.put("Rachaad White", "NFC - Offense");
        ModernNFL.put("D'Andre Swift", "NFC - Offense");
        ModernNFL.put("Aaron Jones", "AFC - Offense");
        ModernNFL.put("Joe Mixon", "NFC - Offense");
        ModernNFL.put("David Montgomery", "NFC - Offense");
        ModernNFL.put("Alvin Kamara", "NFC - Offense");
        ModernNFL.put("De'Von Achane", "AFC - Offense");
        ModernNFL.put("James Conner", "NFC - Offense");
        ModernNFL.put("Brian Robinson", "NFC - Offense");
        ModernNFL.put("Dameon Pierce", "AFC - Offense");
        ModernNFL.put("Tyjae Spears", "AFC - Offense");
        ModernNFL.put("Zamir White", "AFC - Offense");
        ModernNFL.put("Jaylen Warren", "AFC - Offense");
        ModernNFL.put("Jerome Ford", "AFC - Offense");
        ModernNFL.put("Tank Bigsby", "AFC - Offense");
        ModernNFL.put("Roschon Johnson", "NFC - Offense");
        ModernNFL.put("Kendre Miller", "NFC - Offense");
        ModernNFL.put("Zach Charbonnet", "NFC - Offense");
        ModernNFL.put("Tyler Allgeier", "NFC - Offense");
        ModernNFL.put("Elijah Mitchell", "NFC - Offense");
        ModernNFL.put("Kyren Williams", "NFC - Offense");
        ModernNFL.put("Chase Brown", "AFC - Offense");
        ModernNFL.put("Keaton Mitchell", "AFC - Offense");
        ModernNFL.put("Eric Gray", "NFC - Offense");
        ModernNFL.put("Deuce Vaughn", "NFC - Offense");

// Wide Receivers (70)
        ModernNFL.put("Justin Jefferson", "NFC - Offense");
        ModernNFL.put("Ja'Marr Chase", "AFC - Offense");
        ModernNFL.put("CeeDee Lamb", "NFC - Offense");
        ModernNFL.put("Amon-Ra St. Brown", "NFC - Offense");
        ModernNFL.put("A.J. Brown", "NFC - Offense");
        ModernNFL.put("Tyreek Hill", "AFC - Offense");
        ModernNFL.put("Stefon Diggs", "NFC - Offense");
        ModernNFL.put("Davante Adams", "AFC - Offense");
        ModernNFL.put("Garrett Wilson", "AFC - Offense");
        ModernNFL.put("Jaylen Waddle", "AFC - Offense");
        ModernNFL.put("Chris Olave", "NFC - Offense");
        ModernNFL.put("DeVonta Smith", "NFC - Offense");
        ModernNFL.put("Brandon Aiyuk", "NFC - Offense");
        ModernNFL.put("DK Metcalf", "NFC - Offense");
        ModernNFL.put("Tee Higgins", "AFC - Offense");
        ModernNFL.put("Michael Pittman", "AFC - Offense");
        ModernNFL.put("Drake London", "NFC - Offense");
        ModernNFL.put("Christian Kirk", "AFC - Offense");
        ModernNFL.put("Calvin Ridley", "AFC - Offense");
        ModernNFL.put("Deebo Samuel", "NFC - Offense");
        ModernNFL.put("Terry McLaurin", "NFC - Offense");
        ModernNFL.put("Mike Evans", "NFC - Offense");
        ModernNFL.put("Keenan Allen", "NFC - Offense");
        ModernNFL.put("DJ Moore", "NFC - Offense");
        ModernNFL.put("Chris Godwin", "NFC - Offense");
        ModernNFL.put("Jordan Addison", "NFC - Offense");
        ModernNFL.put("Zay Flowers", "AFC - Offense");
        ModernNFL.put("Jaxon Smith-Njigba", "NFC - Offense");
        ModernNFL.put("Rashee Rice", "AFC - Offense");
        ModernNFL.put("Josh Downs", "AFC - Offense");
        ModernNFL.put("Tank Dell", "AFC - Offense");
        ModernNFL.put("Christian Watson", "NFC - Offense");
        ModernNFL.put("George Pickens", "AFC - Offense");
        ModernNFL.put("Jerry Jeudy", "AFC - Offense");
        ModernNFL.put("Diontae Johnson", "AFC - Offense");
        ModernNFL.put("Jameson Williams", "NFC - Offense");
        ModernNFL.put("Kadarius Toney", "AFC - Offense");
        ModernNFL.put("Skyy Moore", "AFC - Offense");
        ModernNFL.put("Wan'Dale Robinson", "NFC - Offense");
        ModernNFL.put("Rashid Shaheed", "NFC - Offense");
        ModernNFL.put("Jonathan Mingo", "NFC - Offense");
        ModernNFL.put("Jayden Reed", "NFC - Offense");
        ModernNFL.put("Marvin Mims", "AFC - Offense");
        ModernNFL.put("Quentin Johnston", "AFC - Offense");
        ModernNFL.put("Joshua Palmer", "AFC - Offense");
        ModernNFL.put("Alec Pierce", "AFC - Offense");
        ModernNFL.put("Romeo Doubs", "NFC - Offense");
        ModernNFL.put("Khalil Shakir", "AFC - Offense");
        ModernNFL.put("Jahan Dotson", "NFC - Offense");
        ModernNFL.put("Elijah Moore", "AFC - Offense");
        ModernNFL.put("Nico Collins", "AFC - Offense");
        ModernNFL.put("Jakobi Meyers", "AFC - Offense");
        ModernNFL.put("Courtland Sutton", "AFC - Offense");
        ModernNFL.put("Marquise Brown", "NFC - Offense");
        ModernNFL.put("Brandin Cooks", "NFC - Offense");
        ModernNFL.put("Adam Thielen", "NFC - Offense");
        ModernNFL.put("Michael Thomas", "NFC - Offense");
        ModernNFL.put("Darnell Mooney", "NFC - Offense");
        ModernNFL.put("Allen Lazard", "AFC - Offense");
        ModernNFL.put("Hunter Renfrow", "AFC - Offense");
        ModernNFL.put("Van Jefferson", "AFC - Offense");
        ModernNFL.put("K.J. Osborn", "NFC - Offense");
        ModernNFL.put("Donovan Peoples-Jones", "NFC - Offense");
        ModernNFL.put("Ray-Ray McCloud", "NFC - Offense");
        ModernNFL.put("DeAndre Hopkins", "AFC - Offense");
        ModernNFL.put("Rome Odunze", "NFC - Offense");
        ModernNFL.put("Malik Nabers", "NFC - Offense");
        ModernNFL.put("Brian Thomas Jr.", "AFC - Offense");
        ModernNFL.put("Xavier Worthy", "AFC - Offense");
        ModernNFL.put("Ladd McConkey", "AFC - Offense");
        ModernNFL.put("Adonai Mitchell", "AFC - Offense");
        ModernNFL.put("Troy Franklin", "AFC - Offense");
        ModernNFL.put("Keon Coleman", "AFC - Offense");
        ModernNFL.put("Xavier Legette", "NFC - Offense");

// Tight Ends (30)
        ModernNFL.put("Travis Kelce", "AFC - Offense");
        ModernNFL.put("Mark Andrews", "AFC - Offense");
        ModernNFL.put("George Kittle", "NFC - Offense");
        ModernNFL.put("Sam LaPorta", "NFC - Offense");
        ModernNFL.put("T.J. Hockenson", "NFC - Offense");
        ModernNFL.put("Kyle Pitts", "NFC - Offense");
        ModernNFL.put("Dalton Kincaid", "AFC - Offense");
        ModernNFL.put("Evan Engram", "AFC - Offense");
        ModernNFL.put("David Njoku", "AFC - Offense");
        ModernNFL.put("Dallas Goedert", "NFC - Offense");
        ModernNFL.put("Cole Kmet", "NFC - Offense");
        ModernNFL.put("Pat Freiermuth", "AFC - Offense");
        ModernNFL.put("Tyler Higbee", "NFC - Offense");
        ModernNFL.put("Gerald Everett", "AFC - Offense");
        ModernNFL.put("Dalton Schultz", "AFC - Offense");
        ModernNFL.put("Noah Fant", "NFC - Offense");
        ModernNFL.put("Mike Gesicki", "AFC - Offense");
        ModernNFL.put("Juwan Johnson", "NFC - Offense");
        ModernNFL.put("Logan Thomas", "NFC - Offense");
        ModernNFL.put("Hunter Henry", "AFC - Offense");
        ModernNFL.put("Isaiah Likely", "AFC - Offense");
        ModernNFL.put("Luke Musgrave", "NFC - Offense");
        ModernNFL.put("Michael Mayer", "AFC - Offense");
        ModernNFL.put("Brenton Strange", "AFC - Offense");
        ModernNFL.put("Tucker Kraft", "NFC - Offense");
        ModernNFL.put("Cade Otton", "NFC - Offense");
        ModernNFL.put("Greg Dulcich", "AFC - Offense");
        ModernNFL.put("Chigoziem Okonkwo", "AFC - Offense");
        ModernNFL.put("Daniel Bellinger", "NFC - Offense");
        ModernNFL.put("Will Mallory", "AFC - Offense");

// Kickers (25)
        ModernNFL.put("Justin Tucker", "AFC - D/ST");
        ModernNFL.put("Harrison Butker", "AFC - D/ST");
        ModernNFL.put("Younghoe Koo", "NFC - D/ST");
        ModernNFL.put("Daniel Carlson", "AFC - D/ST");
        ModernNFL.put("Evan McPherson", "AFC - D/ST");
        ModernNFL.put("Tyler Bass", "AFC - D/ST");
        ModernNFL.put("Jason Myers", "NFC - D/ST");
        ModernNFL.put("Jake Elliott", "NFC - D/ST");
        ModernNFL.put("Brandon Aubrey", "NFC - D/ST");
        ModernNFL.put("Greg Zuerlein", "AFC - D/ST");
        ModernNFL.put("Matt Gay", "AFC - D/ST");
        ModernNFL.put("Blake Grupe", "NFC - D/ST");
        ModernNFL.put("Cameron Dicker", "AFC - D/ST");
        ModernNFL.put("Anders Carlson", "NFC - D/ST");
        ModernNFL.put("Eddy Pineiro", "NFC - D/ST");
        ModernNFL.put("Chase McLaughlin", "AFC - D/ST");
        ModernNFL.put("Jake Moody", "NFC - D/ST");
        ModernNFL.put("Brandon McManus", "NFC - D/ST");
        ModernNFL.put("Wil Lutz", "NFC - D/ST");
        ModernNFL.put("Graham Gano", "NFC - D/ST");
        ModernNFL.put("Chris Boswell", "AFC - D/ST");
        ModernNFL.put("Nick Folk", "AFC - D/ST");
        ModernNFL.put("Dustin Hopkins", "AFC - D/ST");
        ModernNFL.put("Riley Patterson", "AFC - D/ST");
        ModernNFL.put("Cairo Santos", "NFC - D/ST");

// Defensive Linemen (20) - D/ST
        ModernNFL.put("Aaron Donald", "NFC - D/ST");
        ModernNFL.put("Chris Jones", "AFC - D/ST");
        ModernNFL.put("Micah Parsons", "NFC - D/ST");
        ModernNFL.put("Myles Garrett", "AFC - D/ST");
        ModernNFL.put("Nick Bosa", "NFC - D/ST");
        ModernNFL.put("T.J. Watt", "AFC - D/ST");
        ModernNFL.put("Maxx Crosby", "AFC - D/ST");
        ModernNFL.put("Aidan Hutchinson", "NFC - D/ST");
        ModernNFL.put("Trey Hendrickson", "AFC - D/ST");
        ModernNFL.put("Haason Reddick", "NFC - D/ST");
        ModernNFL.put("Quinnen Williams", "AFC - D/ST");
        ModernNFL.put("Jeffery Simmons", "AFC - D/ST");
        ModernNFL.put("Derrick Brown", "NFC - D/ST");
        ModernNFL.put("DeForest Buckner", "AFC - D/ST");
        ModernNFL.put("Jonathan Allen", "NFC - D/ST");
        ModernNFL.put("Cameron Heyward", "AFC - D/ST");
        ModernNFL.put("Kenny Clark", "NFC - D/ST");
        ModernNFL.put("Vita Vea", "NFC - D/ST");
        ModernNFL.put("Dexter Lawrence", "NFC - D/ST");
        ModernNFL.put("Javon Hargrave", "NFC - D/ST");

// Linebackers (20) - D/ST
        ModernNFL.put("Fred Warner", "NFC - D/ST");
        ModernNFL.put("Roquan Smith", "AFC - D/ST");
        ModernNFL.put("Bobby Wagner", "NFC - D/ST");
        ModernNFL.put("Dre Greenlaw", "NFC - D/ST");
        ModernNFL.put("Demario Davis", "NFC - D/ST");
        ModernNFL.put("Lavonte David", "NFC - D/ST");
        ModernNFL.put("Shaquille Leonard", "NFC - D/ST");
        ModernNFL.put("Tremaine Edmunds", "NFC - D/ST");
        ModernNFL.put("Jordyn Brooks", "NFC - D/ST");
        ModernNFL.put("Devin White", "NFC - D/ST");
        ModernNFL.put("Zaire Franklin", "AFC - D/ST");
        ModernNFL.put("Alex Anzalone", "NFC - D/ST");
        ModernNFL.put("Josey Jewell", "NFC - D/ST");
        ModernNFL.put("Frankie Luvu", "NFC - D/ST");
        ModernNFL.put("Kyzir White", "NFC - D/ST");
        ModernNFL.put("Nicholas Morrow", "NFC - D/ST");
        ModernNFL.put("Christian Harris", "AFC - D/ST");
        ModernNFL.put("Jack Campbell", "NFC - D/ST");
        ModernNFL.put("Trenton Simpson", "AFC - D/ST");
        ModernNFL.put("Daiyan Henley", "AFC - D/ST");

// Cornerbacks (20) - D/ST
        ModernNFL.put("Sauce Gardner", "AFC - D/ST");
        ModernNFL.put("Jaire Alexander", "NFC - D/ST");
        ModernNFL.put("Patrick Surtain II", "AFC - D/ST");
        ModernNFL.put("Denzel Ward", "AFC - D/ST");
        ModernNFL.put("Marlon Humphrey", "AFC - D/ST");
        ModernNFL.put("Jaycee Horn", "NFC - D/ST");
        ModernNFL.put("Trevon Diggs", "NFC - D/ST");
        ModernNFL.put("Darius Slay", "NFC - D/ST");
        ModernNFL.put("Marshon Lattimore", "NFC - D/ST");
        ModernNFL.put("Charvarius Ward", "NFC - D/ST");
        ModernNFL.put("L'Jarius Sneed", "AFC - D/ST");
        ModernNFL.put("Kenny Moore II", "AFC - D/ST");
        ModernNFL.put("Tariq Woolen", "NFC - D/ST");
        ModernNFL.put("Devon Witherspoon", "NFC - D/ST");
        ModernNFL.put("Christian Gonzalez", "AFC - D/ST");
        ModernNFL.put("Joey Porter Jr.", "AFC - D/ST");
        ModernNFL.put("Emmanuel Forbes", "NFC - D/ST");
        ModernNFL.put("Deonte Banks", "NFC - D/ST");
        ModernNFL.put("Jaylon Johnson", "NFC - D/ST");
        ModernNFL.put("Steven Nelson", "NFC - D/ST");

// Safeties (20) - D/ST
        ModernNFL.put("Minkah Fitzpatrick", "AFC - D/ST");
        ModernNFL.put("Derwin James", "AFC - D/ST");
        ModernNFL.put("Justin Simmons", "AFC - D/ST");
        ModernNFL.put("Kevin Byard", "NFC - D/ST");
        ModernNFL.put("Budda Baker", "NFC - D/ST");
        ModernNFL.put("Jessie Bates III", "NFC - D/ST");
        ModernNFL.put("Antoine Winfield Jr.", "NFC - D/ST");
        ModernNFL.put("Jevon Holland", "AFC - D/ST");
        ModernNFL.put("Kyle Hamilton", "AFC - D/ST");
        ModernNFL.put("Talanoa Hufanga", "NFC - D/ST");
        ModernNFL.put("Jordan Poyer", "AFC - D/ST");
        ModernNFL.put("Micah Hyde", "AFC - D/ST");
        ModernNFL.put("Xavier McKinney", "NFC - D/ST");
        ModernNFL.put("Jaquan Brisker", "NFC - D/ST");
        ModernNFL.put("Kerby Joseph", "NFC - D/ST");
        ModernNFL.put("Jalen Pitre", "AFC - D/ST");
        ModernNFL.put("Nick Cross", "AFC - D/ST");
        ModernNFL.put("Brian Branch", "NFC - D/ST");
        ModernNFL.put("Sydney Brown", "NFC - D/ST");
        ModernNFL.put("Jason Pinnock", "NFC - D/ST");
    }

    private static void initNFLSkillPostion() {
        // Quarterbacks - Updated for 2025
        NFLSkillPosition.put("Patrick Mahomes", "AFC");
        NFLSkillPosition.put("Josh Allen", "AFC");
        NFLSkillPosition.put("Joe Burrow", "AFC");
        NFLSkillPosition.put("Lamar Jackson", "AFC");
        NFLSkillPosition.put("Justin Herbert", "AFC");
        NFLSkillPosition.put("C.J. Stroud", "AFC");
        NFLSkillPosition.put("Trevor Lawrence", "AFC");
        NFLSkillPosition.put("Anthony Richardson", "AFC");
        NFLSkillPosition.put("Tua Tagovailoa", "AFC");
        NFLSkillPosition.put("Will Levis", "AFC");
        NFLSkillPosition.put("Bryce Young", "NFC");
        NFLSkillPosition.put("Jalen Hurts", "NFC");
        NFLSkillPosition.put("Dak Prescott", "NFC");
        NFLSkillPosition.put("Jordan Love", "NFC");
        NFLSkillPosition.put("Kyler Murray", "NFC");
        NFLSkillPosition.put("Brock Purdy", "NFC");
        NFLSkillPosition.put("Matthew Stafford", "NFC");
        NFLSkillPosition.put("Jared Goff", "NFC");
        NFLSkillPosition.put("Kirk Cousins", "NFC");
        NFLSkillPosition.put("Geno Smith", "NFC");
        NFLSkillPosition.put("Daniel Jones", "NFC");
        NFLSkillPosition.put("Caleb Williams", "NFC");
        NFLSkillPosition.put("Drake Maye", "AFC");
        NFLSkillPosition.put("Jayden Daniels", "NFC");

// Running Backs - Updated for 2025
        NFLSkillPosition.put("Christian McCaffrey", "NFC");
        NFLSkillPosition.put("Bijan Robinson", "NFC");
        NFLSkillPosition.put("Jahmyr Gibbs", "NFC");
        NFLSkillPosition.put("Saquon Barkley", "NFC");
        NFLSkillPosition.put("Travis Etienne", "AFC");
        NFLSkillPosition.put("Jonathan Taylor", "AFC");
        NFLSkillPosition.put("Nick Chubb", "AFC");
        NFLSkillPosition.put("Josh Jacobs", "NFC");
        NFLSkillPosition.put("Derrick Henry", "AFC");
        NFLSkillPosition.put("Tony Pollard", "AFC");
        NFLSkillPosition.put("Rhamondre Stevenson", "AFC");
        NFLSkillPosition.put("James Cook", "AFC");
        NFLSkillPosition.put("Kenneth Walker", "NFC");
        NFLSkillPosition.put("Javonte Williams", "AFC");
        NFLSkillPosition.put("Isiah Pacheco", "AFC");
        NFLSkillPosition.put("Rachaad White", "NFC");
        NFLSkillPosition.put("D'Andre Swift", "NFC");
        NFLSkillPosition.put("Aaron Jones", "AFC");
        NFLSkillPosition.put("Joe Mixon", "NFC");
        NFLSkillPosition.put("David Montgomery", "NFC");
        NFLSkillPosition.put("Alvin Kamara", "NFC");
        NFLSkillPosition.put("De'Von Achane", "AFC");
        NFLSkillPosition.put("James Conner", "NFC");
        NFLSkillPosition.put("Brian Robinson", "NFC");
        NFLSkillPosition.put("Dameon Pierce", "AFC");
        NFLSkillPosition.put("Tyjae Spears", "AFC");
        NFLSkillPosition.put("Zamir White", "AFC");
        NFLSkillPosition.put("Jaylen Warren", "AFC");
        NFLSkillPosition.put("Jerome Ford", "AFC");
        NFLSkillPosition.put("Tank Bigsby", "AFC");
        NFLSkillPosition.put("Roschon Johnson", "NFC");
        NFLSkillPosition.put("Kendre Miller", "NFC");
        NFLSkillPosition.put("Zach Charbonnet", "NFC");
        NFLSkillPosition.put("Tyler Allgeier", "NFC");
        NFLSkillPosition.put("Elijah Mitchell", "NFC");
        NFLSkillPosition.put("Kyren Williams", "NFC");
        NFLSkillPosition.put("Chase Brown", "AFC");
        NFLSkillPosition.put("Keaton Mitchell", "AFC");
        NFLSkillPosition.put("Eric Gray", "NFC");
        NFLSkillPosition.put("Deuce Vaughn", "NFC");
        NFLSkillPosition.put("Jaleel McLaughlin", "AFC");
        NFLSkillPosition.put("Emanuel Wilson", "NFC");

// Wide Receivers - Updated for 2025
        NFLSkillPosition.put("Justin Jefferson", "NFC");
        NFLSkillPosition.put("Ja'Marr Chase", "AFC");
        NFLSkillPosition.put("CeeDee Lamb", "NFC");
        NFLSkillPosition.put("Amon-Ra St. Brown", "NFC");
        NFLSkillPosition.put("A.J. Brown", "NFC");
        NFLSkillPosition.put("Tyreek Hill", "AFC");
        NFLSkillPosition.put("Stefon Diggs", "NFC");
        NFLSkillPosition.put("Davante Adams", "AFC");
        NFLSkillPosition.put("Garrett Wilson", "AFC");
        NFLSkillPosition.put("Jaylen Waddle", "AFC");
        NFLSkillPosition.put("Chris Olave", "NFC");
        NFLSkillPosition.put("DeVonta Smith", "NFC");
        NFLSkillPosition.put("Brandon Aiyuk", "NFC");
        NFLSkillPosition.put("DK Metcalf", "NFC");
        NFLSkillPosition.put("Tee Higgins", "AFC");
        NFLSkillPosition.put("Michael Pittman", "AFC");
        NFLSkillPosition.put("Drake London", "NFC");
        NFLSkillPosition.put("Christian Kirk", "AFC");
        NFLSkillPosition.put("Calvin Ridley", "AFC");
        NFLSkillPosition.put("Deebo Samuel", "NFC");
        NFLSkillPosition.put("Terry McLaurin", "NFC");
        NFLSkillPosition.put("Mike Evans", "NFC");
        NFLSkillPosition.put("Keenan Allen", "NFC");
        NFLSkillPosition.put("DJ Moore", "NFC");
        NFLSkillPosition.put("Chris Godwin", "NFC");
        NFLSkillPosition.put("Jordan Addison", "NFC");
        NFLSkillPosition.put("Zay Flowers", "AFC");
        NFLSkillPosition.put("Jaxon Smith-Njigba", "NFC");
        NFLSkillPosition.put("Rashee Rice", "AFC");
        NFLSkillPosition.put("Josh Downs", "AFC");
        NFLSkillPosition.put("Tank Dell", "AFC");
        NFLSkillPosition.put("Christian Watson", "NFC");
        NFLSkillPosition.put("George Pickens", "AFC");
        NFLSkillPosition.put("Jerry Jeudy", "AFC");
        NFLSkillPosition.put("Diontae Johnson", "AFC");
        NFLSkillPosition.put("Jameson Williams", "NFC");
        NFLSkillPosition.put("Kadarius Toney", "AFC");
        NFLSkillPosition.put("Skyy Moore", "AFC");
        NFLSkillPosition.put("Wan'Dale Robinson", "NFC");
        NFLSkillPosition.put("Rashid Shaheed", "NFC");
        NFLSkillPosition.put("Jonathan Mingo", "NFC");
        NFLSkillPosition.put("Jayden Reed", "NFC");
        NFLSkillPosition.put("Marvin Mims", "AFC");
        NFLSkillPosition.put("Quentin Johnston", "AFC");
        NFLSkillPosition.put("Joshua Palmer", "AFC");
        NFLSkillPosition.put("Alec Pierce", "AFC");
        NFLSkillPosition.put("Romeo Doubs", "NFC");
        NFLSkillPosition.put("Khalil Shakir", "AFC");
        NFLSkillPosition.put("Jahan Dotson", "NFC");
        NFLSkillPosition.put("Elijah Moore", "AFC");
        NFLSkillPosition.put("Nico Collins", "AFC");
        NFLSkillPosition.put("Jakobi Meyers", "AFC");
        NFLSkillPosition.put("Courtland Sutton", "AFC");
        NFLSkillPosition.put("Marquise Brown", "NFC");
        NFLSkillPosition.put("Brandin Cooks", "NFC");
        NFLSkillPosition.put("Adam Thielen", "NFC");
        NFLSkillPosition.put("Michael Thomas", "NFC");
        NFLSkillPosition.put("Darnell Mooney", "NFC");
        NFLSkillPosition.put("Allen Lazard", "AFC");
        NFLSkillPosition.put("Hunter Renfrow", "AFC");
        NFLSkillPosition.put("Van Jefferson", "AFC");
        NFLSkillPosition.put("K.J. Osborn", "NFC");
        NFLSkillPosition.put("Donovan Peoples-Jones", "NFC");
        NFLSkillPosition.put("Ray-Ray McCloud", "NFC");
        NFLSkillPosition.put("DeAndre Hopkins", "AFC");

// Tight Ends - Updated for 2025
        NFLSkillPosition.put("Travis Kelce", "AFC");
        NFLSkillPosition.put("Mark Andrews", "AFC");
        NFLSkillPosition.put("George Kittle", "NFC");
        NFLSkillPosition.put("Sam LaPorta", "NFC");
        NFLSkillPosition.put("T.J. Hockenson", "NFC");
        NFLSkillPosition.put("Kyle Pitts", "NFC");
        NFLSkillPosition.put("Dalton Kincaid", "AFC");
        NFLSkillPosition.put("Evan Engram", "AFC");
        NFLSkillPosition.put("David Njoku", "AFC");
        NFLSkillPosition.put("Dallas Goedert", "NFC");
        NFLSkillPosition.put("Cole Kmet", "NFC");
        NFLSkillPosition.put("Pat Freiermuth", "AFC");
        NFLSkillPosition.put("Tyler Higbee", "NFC");
        NFLSkillPosition.put("Gerald Everett", "AFC");
        NFLSkillPosition.put("Dalton Schultz", "AFC");
        NFLSkillPosition.put("Noah Fant", "NFC");
        NFLSkillPosition.put("Mike Gesicki", "AFC");
        NFLSkillPosition.put("Juwan Johnson", "NFC");
        NFLSkillPosition.put("Logan Thomas", "NFC");
        NFLSkillPosition.put("Hunter Henry", "AFC");
        NFLSkillPosition.put("Isaiah Likely", "AFC");
        NFLSkillPosition.put("Luke Musgrave", "NFC");
        NFLSkillPosition.put("Michael Mayer", "AFC");
        NFLSkillPosition.put("Brenton Strange", "AFC");
        NFLSkillPosition.put("Tucker Kraft", "NFC");
    }
}
